### PR TITLE
Fix handling of paths on Linux and Mac (issue #54)

### PR DESCRIPTION
**Pull request by ermshiperete**
Linux and Mac use a forward slash instead of a backslash to separate
directories. This change makes use of the Path.DirectorySeparatorChar
instead of hardcoding backslash. This allows to use the same code on
all platforms.

This change also adjusts the WindowsNameTransform tests so that they
also work cross-platform.

Incorporated in this PR is #52.

### CODE REVIEW

**Comment by rversaw** [comment]
What's the status of this PR? Is it likely to be accepted soon?

**Comment by odyth** [comment]
Bump.  Any update on this getting merged?

**Comment by jfreilly** [comment]
WindowsNameTransform was never intended to be generic a clue being the name including Windows but this works fine.  It would be good to rename the class but this itself causes issues.

**Comment by ermshiperete** [comment]
My Contribution is licensed under the MIT License.

**Pull request merged**
