### PR TITLE
inline crc32 checksum update, about 2x higher crc throughput

### PR DESCRIPTION
**Pull request by dpethes**
Removes redundant function call for each checked byte. The speedup is most noticeable when decoding highly compressed data, where crc takes a significant amount of time.

_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License._

### CODE REVIEW

**Comment by christophwille** [comment]
Is there a specific reason for removing unchecked() ? Original code in Update(...):
checkValue = unchecked(crcTable[(checkValue ^ bval) & 0xFF] ^ (checkValue >> 8));

**Comment by dpethes** [comment]
It has no measurable effect performance-wise.

**Comment by christophwille** [comment]
well, I think it could have an effect exception-wise (wasn't worrying much about perf):
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/unchecked

**Comment by christophwille** [comment]
"2x higher throughput" - did you measure that with a Release build or where does this number come from? Because I can't imagine that the runtime wouldn't inline this method call.

**Comment by dpethes** [comment]
The crc calculation is doing only bitops, unchecked matters only for arithmetic ops.
IIRC I modified one of the apps in the Samples solution* for the measurement. I used VS2015 release build, but I don't remember if it was run as 32bit or 64bit - most likely latter. Inlining the method isn't enough - it would have to skip updating the checksum field during calculation as well.
If you have some samples for perf testing that you prefer, I could prepare some new measurements.


* I had to fix some references there - is it still broken?

**Comment by piksel** [comment]
See #306

**Pull request closed without merging**
