### PR TITLE
Implemented NETStandard1.3 lib and made changes get lib compiling

### PR DESCRIPTION
**Pull request by zone117x**
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License._

Creating a pull request for review purposes. These changes need reviewed and tested before merging. 

No features were removed during this refactoring other than some exception serialization related stuff. 
- The ZIP AES changes need tested
- The streams were improperly overriding Stream.Close() according to https://msdn.microsoft.com/en-us/library/ms143450(v=vs.110).aspx ... these were changed to Stream.Dispose(bool) but there may be problems around garbage collection - needs reviewed and tested
- Unsupported exception serialization and constructors were removed
- DefaultCodePage changes need reviewed
- Some commenting may need updated

### CODE REVIEW

**Comment by xied75** [comment]
Agree on the change to remove using Stream.Close(), it's no longer exist in the coreclr/corefx.

**Comment by zone117x** [comment]
Separating them is a bit hard because the above changes were the minimum required to get the .netstandard lib to compile at all. 

We could make those individual changes only for the existing lib with netstandard and PR those one at a time, but I don't have time to do that. I got my fork working for my purposes and mostly made this PR to give some head start to the main contributors.

**Comment by xied75** [comment]
If @McNeight is willing to consider merge it, I can volunteer to help the review.

**Comment by jahmai** [comment]
Missed specifying code signing key on the netstandard project.
Also, nuspec not updated.

Otherwise, I have built and modified the existing nuget package by hand and our unit tests that use this still pass, so well done 👍

**Comment by McNeight** [comment]
This is great work! My lingering concern, and the reason why I took so long to finally commit this, is that it breaks some of the automated build and test. I've been hoping to get it cleaned up before now, but I've realized that I need to get the change in and then work on cleaning up.

Any help with getting the automated build and test setup back to normal again would be much appreciated.

-Neil

**Comment by xied75** [comment]
I did a clean clone and trying to build with VS2015up3, somehow I got this error:
```
1>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error : Your project is not referencing the ".NETFramework,Version=v4.5" framework. Add a reference to ".NETFramework,Version=v4.5" in the "frameworks" section of your project.json, and then re-run NuGet restore.
```

In fact I could right click and just build the portable project, but not the main 4.5 project.

Just wondering, netstandard1.3 will support from 4.6, are we going to keep 4.5 project?

**Comment by zone117x** [comment]
This is fixed in my last pull request https://github.com/icsharpcode/SharpZipLib/pull/150

**Pull request merged**
