### PR TITLE
Multiple tweaks and bugfixes

### PR DESCRIPTION
**Pull request by bastianeicher**
I've been maintaing a fork of SharpZipLib with a number of small tweaks and bugfixes. This code has been in heavy use for over a year in [Zero Install](http://0install.de/) and is available on NuGet as [ICSharpCode.SharpZipLib.Patched](https://www.nuget.org/packages/ICSharpCode.SharpZipLib.Patched/).

For the pull request I have rebased everything on the current master and removed anything that would change the publicly visible API. This also includes the commit from #18, which I've been using in my fork.

### CODE REVIEW

**Comment by bastianeicher** [comment]
@McNeight I hereby place the code contributed in my commits under the MIT license.
@hempels Is it fine by you if we include your commit as well?

**Comment by McNeight** [comment]
@bastianeicher 

Have you heard anything from @hempels about re-licensing his contribution? As soon as I get confirmation from him, I'll merge all of the code in.

-Neil

**Comment by hempels** [comment]
Approval was a bit complicated as the company I worked for when I contributed that change was subsequently acquired.
See issue: #103

**Comment by bastianeicher** [comment]
@hempels: Thanks for getting the contribution cleared. :)

@McNeight: I rebased my branch of the current master to make merging easier.

**Comment by McNeight** [comment]
Shawn & Bastian,

Thanks for taking the extra time to square everything away, and thank you for your contributions.

-Neil

**Pull request merged**
