### PR TITLE
[Feature] Add support at .net 3.5  Framework target 

### PR DESCRIPTION
**Pull request by workgroupengineering**
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License._

### CODE REVIEW

**Comment by christophwille** [comment]
What is the point of FW 3.5 support in 2019? Making our code base and build processes more complicated for absolute edge cases is not helpful (we just removed 3.5 support from AvalonEdit for good).

**Comment by workgroupengineering** [comment]
Hi @christophwille 
sorry if I didn't open a problem before creating a pr.

> What is the point of FW 3.5 support in 2019? Making our code base and build processes more complicated is not helpful (we just removed 3.5 support from AvalonEdit for good).

FW 3.5 at now is more diffuse version of .NET Framework. It' is running from oldest win xp at new windows 10.
There is a lot of software compiled with FW 3.5 that cannot be updated since proprietary libraries are not available to the new version of framework. Especially in machine automation.

**Comment by christophwille** [comment]
Yes, it is old. And that is precisely my point - it makes modernizing the library hard. No, we won't re-add support for this ancient framework.

**Comment by workgroupengineering** [comment]
I respect your decision and I will close the PR, but I am not of your opinion.

If an old man continues to do his job well, do I have to treat him if he has a problem?

**Comment by piksel** [comment]
Well, the problem here is that it doesn't do the job equally well. This PR is in itself testament to that. You need workarounds, polyfills and preprocessor directives to get it to work. This means that we have to support code that we normally never run, have to do additional polyfills / backports for new features and as a result, spend less time doing actual development.

**Pull request closed without merging**
