### PR TITLE
Fixed issue by using lower 16 bytes as IV for AES256

### PR DESCRIPTION
**Pull request by FastJack2**
_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License._

### CODE REVIEW

**Comment by piksel** [comment]
Unfortunatly this does not fix the issue. It turns out that the real bug here is the use of key2 as the AES IV. It's only supposed to be used for creating the MAC (which it's also used for atm). Instead, no IV ( all zero bytes ) should be used for AES initialization. 
I still don't know why using key2 as IV works for 128bit AES though...

**Comment by piksel** [comment]
Unmodified test results:
https://ci.appveyor.com/project/icsharpcode/sharpziplib/build/1.0-git88302c5_91/job/vn600e3dgelh77wo/tests
(`System.ArgumentNullException : Buffer cannot be null.`)

IV truncation test results:
https://ci.appveyor.com/project/icsharpcode/sharpziplib/build/job/9hjla7ffnvwn99pe/tests
(`Archive verification failed`)

**Comment by piksel** [comment]
AES256 encrypted zip is now successfully verified by 7-zip.

Btw. @FastJack2, why did you replace `Aes.Create()` with `new AesManaged()`?

**Comment by stealthrabbi** [comment]
Is it possible to merge this in and produce a new release?

**Comment by piksel** [comment]
@stealthrabbi Until v1.1 is released you can get the pre-release nuget packages here:
https://ci.appveyor.com/project/icsharpcode/sharpziplib/build/job/7a2vcixlb41a953f/artifacts

**Pull request merged**
