### PR TITLE
Change TarArchive.ExtractContent() to dispose of output streams in case of an exception

### PR DESCRIPTION
**Pull request by Numpsy**
refs #321 - change TarArchive.ExtractEntry to dispose of output file streams in a finally block, in case an exception occurs. 
(pretty simple change, but it looks like changing the indentation makes the diff viewer make the change look greater than it is).

Also adds a unit test that failed previously and passes now.

_I certify that I own, and have sufficient rights to contribute, all source code and related material intended to be compiled or integrated with the source code for the SharpZipLib open source product (the "Contribution"). My Contribution is licensed under the MIT License._

### CODE REVIEW

**Comment by Numpsy** [comment]
I think at the time I was just trying to make the minimal change to fix the issue.

Possibly the using approach has issues with the way the StreamWriter is only optionally created, but when it is it takes ownership of the output stream such that you don't have to dispose both?
Would have to have another look, perhaps it could do with being refactored to improve that.

**Comment by piksel** [comment]
StreamWriter has a `leaveOpen` parameter, but you have to specify all four parameters:
```public StreamWriter (System.IO.Stream stream, System.Text.Encoding encoding, int bufferSize, bool leaveOpen);```  
Even if the change is small, it's hard to tell what has changed due to the scope change (as you said).

**Comment by Numpsy** [comment]
Hmm, I didn't pay too much attention to what this function was actually doing when I looked at it before, but on a closer look it seems a bit wrong in general. I mean, 

1) The IsBinary check @ https://github.com/icsharpcode/SharpZipLib/blob/27ac139f213a8a2f723b43418130b0098b7e4080/src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs#L631 looks like it's trying to check if the output file is binary, rather than the input data?

2) What's the loop @ https://github.com/icsharpcode/SharpZipLib/blob/27ac139f213a8a2f723b43418130b0098b7e4080/src/ICSharpCode.SharpZipLib/Tar/TarArchive.cs#L653 going to do if there aren't any new lines in the buffer it's going through?

**Comment by piksel** [comment]
I think what it's trying to do is mimic `fopen()` without the `b` mode flag. Basically translating line endings to the target operating systems preferred ones.  
They probably copied the `isBinary` from the archive creation code where it makes much more sense. This test should always return false since it tries to find "binary" data in truncated file. Either way it's wrong.  
  
The loop would just not write anything to the output  if no newlines are encountered. Which also means that the last line would always be omitted.  
Instead of this code, simply using `StreamReader.ReadLine()` followed by `StreamWriter.WriteLine()`  would replace the line endings.

**Comment by Numpsy** [comment]
that seems more reasonable (was also thinking that the existing code will have issues if the input already has Windows line endings, and that would fix that as well).

This is going on a bit of a tangent though - i'll refactor the stream disposal to use usings, and then see about a seperate issue for the rest.

**Comment by Numpsy** [comment]
I've changed it to use using blocks and also to just use TarInputStream.CopyEntryContents in the non-translate cases.
I haven't made any changes to the binary detection or line handling in this set - will open a seprate issue about that.

**Comment by Numpsy** [comment]
Actually, I wonder if the usage of IsBinary there is actually the cause of #27, where trying to open the file for read while it's already open for create/write caues the exception?

**Comment by piksel** [comment]
Good catch! That actually also answers the question "how did this ever work?". It's probably never even turned on.  
Since the write file handle is always acquired (without Read sharing permitted) this would always fail (on windows).

**Pull request merged**
